# The native renderer uses Dawn; the web renderer uses its matching C++ API over browser WebGPU.
# Port instructions: https://dawn.googlesource.com/dawn/+/refs/heads/main/src/emdawnwebgpu/pkg/README.md
if(EMSCRIPTEN)
    set(YOREHOLD_WEBGPU_PORT "emdawnwebgpu" CACHE STRING "Emscripten WebGPU port name or path to a pinned port file")
    add_library(yorehold-webgpu INTERFACE)
    target_compile_options(yorehold-webgpu INTERFACE "--use-port=${YOREHOLD_WEBGPU_PORT}")
    target_link_options(yorehold-webgpu INTERFACE "--use-port=${YOREHOLD_WEBGPU_PORT}" -sASYNCIFY=1 -sASYNCIFY_STACK_SIZE=65536 -sALLOW_MEMORY_GROWTH=1)
    set(YOREHOLD_WEBGPU_TARGET yorehold-webgpu)
else()
    find_package(Threads REQUIRED)
    set(YOREHOLD_DAWN_VERSION "v20260930.214659")
    set(YOREHOLD_DAWN_COMMIT "9af2744f8d6f0bd97a8d37b3910ba7637a3d0a90")
    set(YOREHOLD_DEPS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../.deps" CACHE PATH "Shared dependency download folder")
    set(dawn_dir "${YOREHOLD_DEPS_DIR}/dawn-${YOREHOLD_DAWN_VERSION}")
    if(WIN32)
        set(dawn_source_default OFF)
    else()
        set(dawn_source_default ON)
    endif()
    option(YOREHOLD_DAWN_FROM_SOURCE "Build pinned Dawn instead of using a binary package" ${dawn_source_default})
    if(YOREHOLD_DAWN_FROM_SOURCE)
        # An installed native package takes precedence; this also supports cross-compiled mobile SDKs.
        find_package(Dawn CONFIG QUIET)
        if(NOT Dawn_FOUND)
            set(DAWN_FETCH_DEPENDENCIES ON CACHE BOOL "" FORCE)
            set(DAWN_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
            set(DAWN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
            set(TINT_BUILD_TESTS OFF CACHE BOOL "" FORCE)
            set(TINT_BUILD_CMD_TOOLS OFF CACHE BOOL "" FORCE)
            set(DAWN_ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
            FetchContent_Declare(dawn GIT_REPOSITORY https://dawn.googlesource.com/dawn GIT_TAG ${YOREHOLD_DAWN_COMMIT})
            FetchContent_MakeAvailable(dawn)
        endif()
    else()
        if(NOT EXISTS "${dawn_dir}/lib/cmake/Dawn/DawnConfig.cmake")
            if(NOT WIN32)
                message(FATAL_ERROR "Pass -DDawn_DIR=<native Dawn package> or -DYOREHOLD_DAWN_FROM_SOURCE=ON")
            endif()
            set(dawn_name "Dawn-${YOREHOLD_DAWN_COMMIT}-windows-latest-Release")
            file(MAKE_DIRECTORY "${YOREHOLD_DEPS_DIR}")
            message(STATUS "Downloading Dawn ${YOREHOLD_DAWN_VERSION} (first configure only)")
            file(DOWNLOAD "https://github.com/google/dawn/releases/download/${YOREHOLD_DAWN_VERSION}/${dawn_name}.tar.gz"
                "${YOREHOLD_DEPS_DIR}/dawn.tar.gz" SHOW_PROGRESS STATUS download_status)
            list(GET download_status 0 download_code)
            if(NOT download_code EQUAL 0)
                message(FATAL_ERROR "Dawn download failed: ${download_status}")
            endif()
            file(ARCHIVE_EXTRACT INPUT "${YOREHOLD_DEPS_DIR}/dawn.tar.gz" DESTINATION "${YOREHOLD_DEPS_DIR}")
            file(RENAME "${YOREHOLD_DEPS_DIR}/${dawn_name}" "${dawn_dir}")
            file(REMOVE "${YOREHOLD_DEPS_DIR}/dawn.tar.gz")
        endif()
        find_package(Dawn REQUIRED CONFIG PATHS "${dawn_dir}" NO_DEFAULT_PATH)
    endif()
    if(TARGET dawn::webgpu_dawn)
        set(YOREHOLD_WEBGPU_TARGET dawn::webgpu_dawn)
    elseif(TARGET webgpu_dawn)
        set(YOREHOLD_WEBGPU_TARGET webgpu_dawn)
    else()
        message(FATAL_ERROR "Dawn package did not provide a WebGPU target")
    endif()
endif()

function(yorehold_platform_app target)
    if(EMSCRIPTEN)
        set_target_properties(${target} PROPERTIES SUFFIX ".html")
        target_link_options(${target} PRIVATE
            "SHELL:--preload-file ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../assets@/framework-assets")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        set_target_properties(${target} PROPERTIES MACOSX_BUNDLE TRUE)
    endif()
endfunction()
